[package]
id = "l7qgyikl7wwmkw4zflabf2pgak3qdro7"
name = "zombie_anims"
version = "0.0.1"
content = { type = "Playable" }
ambient_version = "0.3.1-nightly-2023-10-09"

[dependencies]
dead_meets_lead_content = { deployment = "2wTJ0qyUc6i9ggd25geRAC" }
unit = { deployment = "1vBEs82ZnSYQEuJjsT0eYh" }
game_object = { deployment = "77lZ5MG77Hc0GOE5sXU3KG" }

# game_object = { path = "../../../ambient/guest/rust/packages/schemas/game_object" }
# unit_schema = { path = "../../../ambient/guest/rust/packages/schemas/unit" }


[components]
zombie_anims = { type = "EntityId", attributes = ["Networked"] }
